### ISSUE TITLE
skeleton 3 Twitter Bootstrap copies twitter-bootstrap vendor folder twice

### ISSUE THREAD

**Issue by barbalex** [docpad/docpad#1025]
The folder is copied in src > static AND in src > files

This provokes errors leading to memory overflow when running `docpad run`

Well, it is worse: The Project worked fine for a while though there were error messages which I ignored because it worked all the same. But suddenly bang! errors and memory overflow.

I set back the project to an earlier state and it worked. Developed a while. All of a sudden: bang! errors and memory overflow.

I first did not realize what was wrong because on Windows the error overflow prevented me from reading the first error messages. Then I tried it on Mac OsX and was able to read the first error messages. They mentioned the same folder being built twice.

Removing the vendor folder in src > files solves the memory overflow. I am left with the error #1026 which I am not sure if it is related so I opened a separate issue.

EDIT:
Seems loke the files folder in src that contains the vendor folder with the twitter-bootstrap folder is regenerated when trying to build which creates the many errors followed by memory overflow again.

The workflow is like this:
- `docpad run` > many errors and memory overflow
- I delete the files folder in src
- `docpad run` > error #1026
- another `docpad run` > many errors and memory overflow

In case it helps: This is the project: https://github.com/barbalex/blue-borders

EDIT 2:
The files folder gets regenerated on every docpad run because of this code in docpad.coffee:

```
    plugins:
        downloader:
            downloads: [
                {
                    name: 'Bootstrap'
                    path: 'src/files/vendor/twitter-bootstrap'
                    url: 'https://codeload.github.com/twbs/bootstrap/tar.gz/master'
                    tarExtractClean: true
                }
            ]
```

I changed

```
path: 'src/files/vendor/twitter-bootstrap'
```

to

```
path: 'src/static/vendor/twitter-bootstrap'
```

and all that remains is issue #1026
