### ISSUE TITLE
Default plugin config is not overridden with docpad config?

### ISSUE THREAD

**Issue by emirotin** [docpad/docpad#313]
I'm probably doing something wrong, but I'm stuck

I've created a simple plugin: https://github.com/emirotin/docpad-plugin-client-jade. It's structure is completely developed after docpad-plugin-sass
Now in my test project (https://github.com/emirotin/zombie) I have:

```
plugins:
  cjade:
    namespace: 'window.JST'
  sass:
    compass: true
```

Now, I see that for the `sass` plugin `compass` value does properly override plugin's default (false).
But for my own `cjade` the `namespace` is still 'JST' as defined in the plugin.

Please help :)
