### ISSUE TITLE
Make the plugin tester file optional

### ISSUE THREAD

**Issue by balupton** [docpad/docpad#487]
We should also scan the test/package.json file for plugins and auto add them to:

```
# Export Plugin Tester
module.exports = (testers) ->
    # Define My Tester
    class MyTester extends testers.RendererTester
        # Configuration
        docpadConfig:
            enabledPlugins:
                'text': true
                'eco': true
                'marked': true
```

If needed.
