### ISSUE TITLE
Meta data removal bug. Affecting layouts.

### ISSUE THREAD

**Issue by ghost** [docpad/docpad#517]
Add a parameter to a document that another file utilizes (so for this case an index of writings); then, remove that parameter. The layout fails to recognize that removed parameter.

``` yaml

---
title: 'Kindle Paperwhite is Magic.'
date: 'June 01 2013 04:32 AM'
description: 'A review of the Kindle Paperwhite'
layout: 'writing'
tags:
  - reading
  - books
  - e-reader
  - e-ink
  - paperwhite
  - kindle
  - amazon

---
```

Then, remove the description and assume the template no longer utilizes the description.

``` yaml

---
title: 'Kindle Paperwhite is Magic.'
date: 'June 01 2013 04:32 AM'
layout: 'writing'
tags:
  - reading
  - books
  - e-reader
  - e-ink
  - paperwhite
  - kindle
  - amazon

---
```

The template persists in rendering a value that no longer exists; it isn't being removed from the model that the template has. However, when I did a raw query with the DocPad API the property was removed.

The only work around is to manually set the value to false `description:false` then the value is updated. So it appears that removing the value did not update the model.

Here is the index code:

``` html
<% writings = @getFilesAtPath('./writing/', {date: -1}); %>

  <% if writings.length: %>

    <ul class="items">

    <% for writing in writings.models: %>
      <li>
         <%- writing.get('title') %>

        <% console.log(writing.get('description')); %>

        <% if writing.get('description'): %>
          <blockquote><p class="description"><%- writing.get('description'); %></p></blockquote>
        <% end %>
      </li>
    <% end %>

    </ul>

  <% else: %>
    <p>No writing</p>
  <% end %>
```
