### ISSUE TITLE
The discussion of meta only docs.

### ISSUE THREAD

**Issue by ghost** [docpad/docpad#541]
We need a solution for meta only content, which essentially means database only content and it should not be served by the server. We could query it with plugins like eco or via the API.

Example:

``` yaml

---
who: 'Joshua Anderson'
what: 'went to the park'
why: 'to fetch a pail of water: oh.'

---
```

This data could then be queried and used for purposes other than serving a static file.
