### ISSUE TITLE
Document dates set by 'date' yaml metadata are off by a day in collections

### ISSUE THREAD

**Issue by jonphipps** [docpad/docpad#818]
So here's a file's yaml metadata:

``` yaml

---
title: This is Blog Post &num;3
layout: post
tags: ['intro','post']
date: 2014-02-24

---
```

here's the `index.html.jade` template:

``` jade
nav.linklist
  each doc in getCollection('posts').toJSON()
    li
      span= doc.date.toDateString()
      |  &raquo;&nbsp;
      a(href=doc.url)!= doc.title
```

and here's the generated index.html:

``` html
<li>
  <span>
    Sun Feb 23 2014
  </span>
  »
  <a href="/posts/hello3.html">
    This is Blog Post #3
  </a>
</li>
```

Note that the `doc.date.toDateString()` is off by a day. I would assume that it might be a timezone problem, but if that were the case then it would more likely be advanced by a day since my current timezone is either GMT or GMT-5 and this was generated about 5pm GMT-5.
